InstanciaProyectoSTF:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c101f26f147fa7fd
      KeyName: vockey
      SecurityGroups:
        - !Ref MiSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Actualizamos paquetes e instalamos Docker y Git (usando dnf, el nuevo estándar)
          dnf update -y
          dnf install docker -y
          dnf install git -y
          
          # Arrancamos el servicio de Docker
          systemctl start docker
          systemctl enable docker
          
          # Permisos para que el usuario ec2-user pueda usar docker (opcional para el script)
          usermod -a -G docker ec2-user
          
          # Clonamos tu repo y levantamos la app
          cd /home/ec2-user
          git clone https://github.com/SalmuleFish/avanceDeProyectoTest-DevOps.git
          cd avanceDeProyectoTest-DevOps
          
          # Construimos y corremos el contenedor
          docker build -t mi-app .
          docker run -d -p 5000:5000 mi-app