AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue de infraestructura para el proyecto STF

Resources: # <--- ESTO ES LO QUE TE FALTA
  InstanciaProyectoSTF:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c101f26f147fa7fd
      KeyName: vockey
      SecurityGroups:
        - !Ref MiSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          yum install git -y
          cd /home/ec2-user
          git clone https://github.com/SalmuleFish/avanceDeProyectoTest-DevOps.git
          cd avanceDeProyectoTest-DevOps
          docker build -t mi-app .
          docker run -d -p 5000:5000 mi-app

  MiSecurityGroup: # Asegurate de tenerlo definido abajo
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir trafico SSH y Flask
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0